### ISSUE TITLE
Trees - gimme trees!

### ISSUE THREAD

**Issue by ghost** [AgoutiGames/GameOff-2019-Plantower#4]
![birch_comp2](https://user-images.githubusercontent.com/37266387/68280515-f9c78e80-0075-11ea-8ab9-64247813191c.png)
![trees_sketch](https://user-images.githubusercontent.com/37266387/68280516-f9c78e80-0075-11ea-93fb-8a58bab1b707.png)
Okay, we have three kinds of trees so far: a spruce, an oak and a birch. That's pretty good. 

But I think there might be a few more trees. Variety makes the map more interesting.
... and there must be one or two withered trees. Dead trees. So that it looks more diverse.

**Comment by VectorWolf** [comment]
This really matches great with the style we originally had in mind! Great work! 
I think some bushes or some kind of high grass also would fit in nicely. Maybe some flowers? I'm thinking about what would make our biome "complete", a little checklist or something. Dead trees, bushes, grass and flowers and we have a really diverse little forest :-)
